# Generated by Django 6.0.4 on 2026-04-26 05:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('text', 'Text Input'), ('image', 'Image Upload')], default='text', max_length=10)),
                ('raw_text', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('scam_score', models.PositiveSmallIntegerField(default=0)),
                ('confidence_level', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.TextField(blank=True, default='')),
                ('red_flags', models.JSONField(blank=True, default=list)),
                ('green_flags', models.JSONField(blank=True, default=list)),
                ('is_scam', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Job Report',
                'verbose_name_plural': 'Job Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
