runtime: python314
instance_class: F1
entrypoint: gunicorn -b :$PORT server.wsgi:application

handlers:
  - url: /static
    static_dir: staticfiles
  - url: /.*
    script: auto
    secure: always

env_variables:
  DEBUG: "False"
